/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controller.DichVu_bus;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nxnam
 */
public class panel_QuanLyDichVu extends javax.swing.JPanel {
     private DichVu_bus dichvu_Bus = new DichVu_bus();
     private DefaultTableModel modelChiTietDichVu = new DefaultTableModel();
    /**
     * Creates new form Panel_QuanLyDichVu
     */
    public panel_QuanLyDichVu() {
       String cols[] = {"STT","Hình ảnh","Mã dịch vụ","Tên dịch vụ","Số lượng","Giá bán","Loại","Sửa","Xóa","Chọn"};
       modelChiTietDichVu = new DefaultTableModel(cols,0);
       initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnlTimKiem = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        cbxLoaiDichVu = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        pnlNutNhan = new javax.swing.JPanel();
        btnLamMoi = new javax.swing.JButton();
        btnThemDichVu = new javax.swing.JButton();
        btnXoaDichVu = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        spDanhSachDichVu = new javax.swing.JScrollPane();
        tblDanhSachDichVu = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTieuDe.setBackground(new java.awt.Color(153, 255, 255));
        pnlTieuDe.setAlignmentX(0.0F);
        pnlTieuDe.setAlignmentY(0.0F);
        pnlTieuDe.setPreferredSize(new java.awt.Dimension(1366, 80));
        pnlTieuDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setText("QUẢN LÝ DỊCH VỤ");
        pnlTieuDe.add(lblTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        add(pnlTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 60));

        pnlTimKiem.setBackground(new java.awt.Color(204, 204, 204));
        pnlTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTimKiem.setPreferredSize(new java.awt.Dimension(1366, 40));
        pnlTimKiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Có tất cả");
        pnlTimKiem.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setPreferredSize(new java.awt.Dimension(10, 10));
        pnlTimKiem.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 20, 20));

        jLabel3.setText("dịch vụ");
        pnlTimKiem.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        pnlTimKiem.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, -1, -1));

        cbxLoaiDichVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại dịch vụ", "Nước uống ", "Thức ăn nóng", "Thức ăn nhanh" }));
        cbxLoaiDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiDichVuActionPerformed(evt);
            }
        });
        pnlTimKiem.add(cbxLoaiDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));
        pnlTimKiem.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 140, -1));

        lblTimKiem.setText("Tìm kiếm:");
        pnlTimKiem.add(lblTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 15, -1, -1));

        add(pnlTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1366, 40));

        pnlNutNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlNutNhan.setPreferredSize(new java.awt.Dimension(1366, 10));
        pnlNutNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlNutNhan.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        btnThemDichVu.setText("Thêm dịch vụ");
        btnThemDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemDichVuMouseClicked(evt);
            }
        });
        btnThemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDichVuActionPerformed(evt);
            }
        });
        pnlNutNhan.add(btnThemDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnXoaDichVu.setText("Xóa dịch vụ");
        btnXoaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDichVuActionPerformed(evt);
            }
        });
        pnlNutNhan.add(btnXoaDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        add(pnlNutNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1366, 45));

        pnlTable.setBackground(new java.awt.Color(204, 204, 204));
        pnlTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTable.setPreferredSize(new java.awt.Dimension(1366, 610));
        pnlTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSachDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDanhSachDichVu.setModel(modelChiTietDichVu);
        tblDanhSachDichVu.setGridColor(new java.awt.Color(255, 255, 255));
        spDanhSachDichVu.setViewportView(tblDanhSachDichVu);

        pnlTable.add(spDanhSachDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 610));
        pnlTable.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, -1, -1));

        add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 145, 1360, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void cbxLoaiDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiDichVuActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemDichVuActionPerformed

    private void btnXoaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaDichVuActionPerformed

    private void btnThemDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemDichVuMouseClicked
      new JDialogThemDichVu(null, true).show();
    }//GEN-LAST:event_btnThemDichVuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemDichVu;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaDichVu;
    private javax.swing.JComboBox<String> cbxLoaiDichVu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnlNutNhan;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JPanel pnlTimKiem;
    private javax.swing.JScrollPane spDanhSachDichVu;
    private javax.swing.JTable tblDanhSachDichVu;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
